name: Check

on: [ push, pull_request ]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check coveralls --parallel
